name = "venity-api"
main = "src/index.ts"
compatibility_date = "2024-10-13"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[vars]
CONVEX_URL = "https://your-convex-deployment-url.convex.cloud"
JWT_SECRET = "colinsdev"



[[kv_namespaces]]
binding = "VENITY_CACHE"
id = "julius-venity"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1